# Generated by Django 6.0.3 on 2026-07-10 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bandas', '0004_banda_notas_confidenciales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.DateTimeField()),
                ('precio_preventa', models.DecimalField(decimal_places=0, help_text='Precio de Preventa', max_digits=8)),
                ('precio_puerta', models.DecimalField(decimal_places=0, help_text='Precio el día del evento', max_digits=8)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('poster', models.ImageField(blank=True, help_text='Afiche del evento (Ideal 1080x1080)', null=True, upload_to='eventos/posters/')),
                ('link_entrada', models.URLField(blank=True, help_text='Link de ticketera o enlace de WhatsApp para compra', null=True)),
                ('asistencia', models.PositiveIntegerField(default=0, help_text='Asistencia esperada o acumulada')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('notas_confidenciales', models.TextField(blank=True, help_text='Notas internas y acuerdos financieros con la banda', null=True)),
                ('banda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='bandas.banda')),
            ],
        ),
    ]
