# Generated by Django 6.0.3 on 2026-08-02 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarteleraMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveSmallIntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], verbose_name='Mes')),
                ('anio', models.PositiveSmallIntegerField(verbose_name='Año')),
                ('imagen', models.ImageField(help_text='Cartelera mensual (ideal 1080x1350 px)', upload_to='eventos/carteleras/')),
                ('descripcion', models.TextField(blank=True, help_text='Texto opcional para la página de cartelera.')),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cartelera mensual',
                'verbose_name_plural': 'Carteleras mensuales',
                'ordering': ['-anio', '-mes'],
                'constraints': [models.UniqueConstraint(fields=('mes', 'anio'), name='cartelera_unica_mes_anio')],
            },
        ),
    ]
