# Generated by Django 6.0.3 on 2026-07-09 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banda',
            name='dossier',
            field=models.TextField(blank=True, help_text='Descripción o reseña tipo dossier de la banda', null=True),
        ),
    ]
