# Generated by Django 6.0.3 on 2026-07-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0003_fotobanda'),
    ]

    operations = [
        migrations.AddField(
            model_name='banda',
            name='notas_confidenciales',
            field=models.TextField(blank=True, help_text='Notas privadas de Producción', null=True),
        ),
    ]
