# Generated by Django 6.0.3 on 2026-07-14 00:16

import bandas.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0004_banda_notas_confidenciales'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotobanda',
            name='imagen',
            field=models.ImageField(upload_to='galeria_bandas/', validators=[bandas.models.validar_peso_imagen]),
        ),
        migrations.CreateModel(
            name='GaleriaGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título de la foto')),
                ('categoria', models.CharField(choices=[('murales', 'Murales'), ('exposiciones', 'Exposiciones'), ('infraestructura', 'Infraestructura / Local'), ('otros', 'Otros')], default='otros', max_length=50)),
                ('imagen', models.ImageField(upload_to='galerias/', validators=[bandas.models.validar_peso_imagen])),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foto de Galería',
                'verbose_name_plural': 'Fotos de Galerías',
            },
        ),
    ]
