# Generated by Django 6.0.3 on 2026-07-17 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0006_album_fotoalbum_delete_galeriageneral'),
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotobanda',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fotos_galeria', to='eventos.evento'),
        ),
    ]
