# Generated by Django 6.0.3 on 2026-09-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0007_fotobanda_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='tipo',
            field=models.CharField(choices=[('local', 'Galería del local'), ('exposicion', 'Exposición')], default='local', max_length=20, verbose_name='Sección'),
        ),
    ]
