# Generated by Django 5.2.17 on 2026-09-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0007_fotobanda_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banda',
            name='correo',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='banda',
            name='responsable',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='banda',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
