# Generated by Django 6.0.3 on 2026-09-12 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0008_album_tipo_alter_banda_correo_and_more'),
        ('bandas', '0008_alter_banda_correo_alter_banda_responsable_and_more'),
    ]

    operations = [
    ]
